M48
; DRILL file {KiCad 9.0.6} date 2025-12-29T20:27:27-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-29T20:27:27-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X20.6Y-52.11
X20.6Y-57.89
T2
X17.3Y-26.25
X46.5Y-34.75
T3
X17.0Y-17.0
X17.0Y-85.0
X55.0Y-17.0
X55.0Y-85.0
M30
