M48
; DRILL file {KiCad 9.0.6} date 2025-12-30T19:39:21-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T19:39:21-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X20.6Y-52.11
X20.6Y-57.89
T2
X17.0Y-17.0
X17.0Y-85.0
X55.0Y-17.0
X55.0Y-85.0
M30
